"use client"

import { useEffect, useMemo, useState } from "react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { callAgentStream } from "@/lib/agents/client"
import { SDLCShell } from "@/components/sdlc-shell"
import { withProjectQuery } from "@/lib/backend/project-url"
import type { ProjectState, StoryVariant } from "@/lib/backend/types"

const variantLabels = ["A", "B", "C"] as const

function extractSecurityFindings(content: string) {
  const auditMatch = content.match(/AUDIT:\s*(\{[\s\S]*\})/i)
  if (!auditMatch) return { summary: content, findings: [] as StoryVariant["securityFindings"] }
  try {
    const parsed = JSON.parse(auditMatch[1]) as {
      complianceScore?: number
      issues?: Array<{ severity?: "low" | "medium" | "high"; title?: string; description?: string }>
    }
    return {
      summary: `Compliance score ${parsed.complianceScore ?? "n/a"}`,
      findings: (parsed.issues ?? []).map((item) => ({
        severity: item.severity ?? "medium",
        title: item.title ?? "Security finding",
        detail: item.description ?? "",
      })),
    }
  } catch {
    return { summary: content, findings: [] as StoryVariant["securityFindings"] }
  }
}

function safeEvalResult(content: string) {
  const match = content.match(/\{[\s\S]*\}/)
  if (!match) return null
  try {
    return JSON.parse(match[0]) as Record<string, { pros?: string[]; cons?: string[] }>
  } catch {
    return null
  }
}

export function ImplementationWorkspace({ initialProject, projectId }: { initialProject: ProjectState; projectId: string }) {
  const [project, setProject] = useState(initialProject)
  const [runningStoryId, setRunningStoryId] = useState("")
  const [openStoryId, setOpenStoryId] = useState(initialProject.userStories[0]?.id ?? "")
  const [selectedWorkspaceFileId, setSelectedWorkspaceFileId] = useState(initialProject.workspace.selectedFileId || initialProject.workspace.files[0]?.id || "")

  async function patchProject(body: unknown) {
    const response = await fetch(withProjectQuery("/api/project", projectId), {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
    })
    return (await response.json()) as ProjectState
  }

  async function runStoryImplementation(storyId: string) {
    const story = project.userStories.find((item) => item.id === storyId)
    if (!story) return

    setRunningStoryId(storyId)
    try {
      const variants: StoryVariant[] = []

      for (const variantId of variantLabels) {
        const reasoning = await callAgentStream(
          { role: "reasoning", storyId: story.id, storyTitle: story.title, storyDescription: story.summary, variantId },
          () => {}
        )
        const orchestration = await callAgentStream(
          {
            role: "orchestrator",
            storyId: story.id,
            storyTitle: story.title,
            storyDescription: story.summary,
            variantId,
            context: reasoning,
          },
          () => {}
        )
        const backendCode = await callAgentStream(
          { role: "backend", storyId: story.id, storyTitle: story.title, storyDescription: story.summary, variantId, context: orchestration },
          () => {}
        )

        const needsFrontend = /Needs Frontend:\s*yes/i.test(reasoning)
        const frontendCode = needsFrontend
          ? await callAgentStream(
              { role: "frontend", storyId: story.id, storyTitle: story.title, storyDescription: story.summary, variantId, context: orchestration },
              () => {}
            )
          : ""

        const securityOutput = await callAgentStream(
          {
            role: "security",
            storyId: story.id,
            storyTitle: story.title,
            storyDescription: story.summary,
            variantId,
            context: `BACKEND\n${backendCode}\n\nFRONTEND\n${frontendCode || "NONE"}`,
          },
          () => {}
        )

        const security = extractSecurityFindings(securityOutput)
        variants.push({
          id: `${story.id}-VAR-${variantId}`,
          label: `Variant ${variantId}`,
          teamName: `Orchestrator + FE + BE · ${variantId}`,
          focus: `Implementation variant ${variantId}`,
          architecture: orchestration.split("\n")[1] ?? "Agent-coordinated implementation",
          pros: [],
          cons: [],
          tradeoff: "Generated by multi-agent implementation flow.",
          code: [backendCode, frontendCode].filter(Boolean).join("\n\n"),
          reasoning,
          orchestration,
          backendCode,
          frontendCode,
          securitySummary: security.summary,
          securityFindings: security.findings,
        })
      }

      const evaluation = await callAgentStream(
        {
          role: "evaluator",
          storyId: story.id,
          storyTitle: story.title,
          storyDescription: story.summary,
          context: variants
            .map((variant) => `${variant.label}\nReasoning:\n${variant.reasoning}\nSecurity:\n${variant.securitySummary}`)
            .join("\n\n"),
        },
        () => {}
      )

      const evalJson = safeEvalResult(evaluation)
      const enriched = variants.map((variant, index) => {
        const key = variantLabels[index]
        const item = evalJson?.[key]
        return {
          ...variant,
          pros: item?.pros ?? [`${variant.label} is available for comparison.`],
          cons: item?.cons ?? ["No detailed evaluator feedback was parsed."],
        }
      })

      const next = await patchProject({ type: "save-story-variants", storyId: story.id, variants: enriched })
      setProject(next)
    } finally {
      setRunningStoryId("")
    }
  }

  async function chooseVariant(storyId: string, variantId: string) {
    const next = await patchProject({ type: "select-variant", storyId, variantId })
    setProject(next)
    setSelectedWorkspaceFileId(next.workspace.selectedFileId || next.workspace.files[0]?.id || "")
  }

  useEffect(() => {
    if (!project.workspace.files.some((file) => file.id === selectedWorkspaceFileId)) {
      setSelectedWorkspaceFileId(project.workspace.selectedFileId || project.workspace.files[0]?.id || "")
    }
  }, [project.workspace.files, project.workspace.selectedFileId, selectedWorkspaceFileId])

  const activeWorkspaceFile =
    project.workspace.files.find((file) => file.id === selectedWorkspaceFileId) ??
    project.workspace.files.find((file) => file.id === project.workspace.selectedFileId) ??
    project.workspace.files[0]

  return (
    <SDLCShell
      active="implementation"
      projectId={projectId}
      title="Implementation"
      subtitle="Fiecare user story are 3 variante, iar acum poți vedea mai clar reasoning-ul, codul generat și varianta selectată înainte de preview."
      workspaceFiles={project.workspace.files.map((file) => ({ id: file.id, path: file.path }))}
      selectedFileId={selectedWorkspaceFileId}
      onSelectFile={setSelectedWorkspaceFileId}
      previewUrl={withProjectQuery("/api/preview", projectId)}
    >
      <div className="space-y-6">
        <Card className="overflow-hidden rounded-[16px] border-border/40 bg-card/70 p-6">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <div className="text-[11px] font-mono uppercase tracking-[0.18em] text-primary">Implementation Teams</div>
              <h2 className="mt-1 text-2xl font-semibold tracking-tight text-foreground">3 Variants Per User Story</h2>
              <p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">
                Selectezi un story, vezi variantele în format de review tehnic și alegi una care se proiectează direct în workspace pentru preview.
              </p>
            </div>
            <Badge variant="outline" className="border-primary/30 bg-primary/10 text-primary">
              Agent model fallback active
            </Badge>
          </div>
        </Card>

        <div className="grid gap-6 xl:grid-cols-[300px_minmax(0,1fr)]">
          <Card className="rounded-[16px] border-border/40 bg-card/70 p-4">
            <div className="text-[11px] font-mono uppercase tracking-[0.18em] text-primary">Stories</div>
            <div className="mt-4 space-y-3">
              {project.userStories.map((story) => {
                const selectedVariant = story.variants.find((variant) => variant.id === story.selectedVariantId)
                const isActive = openStoryId === story.id
                return (
                  <button
                    key={story.id}
                    type="button"
                    onClick={() => setOpenStoryId(story.id)}
                    className={`w-full rounded-2xl border px-4 py-4 text-left transition ${
                      isActive
                        ? "border-primary/40 bg-primary/10 shadow-sm"
                        : "border-border/40 bg-background/60 hover:border-primary/25 hover:bg-background"
                    }`}
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div>
                        <div className="text-[11px] font-mono uppercase tracking-[0.14em] text-primary">{story.id}</div>
                        <div className="mt-1 text-sm font-semibold text-foreground">{story.title}</div>
                      </div>
                      <Badge variant="outline">{story.storyPoints ? `${story.storyPoints} SP` : story.estimate}</Badge>
                    </div>
                    <p className="mt-2 line-clamp-3 text-xs leading-relaxed text-muted-foreground">{story.summary}</p>
                    <div className="mt-3 text-[11px] text-muted-foreground">
                      Selected: <span className="font-medium text-foreground">{selectedVariant?.label ?? "None"}</span>
                    </div>
                  </button>
                )
              })}
            </div>
          </Card>

          <div className="space-y-6">
            {project.userStories
              .filter((story) => story.id === openStoryId)
              .map((story) => (
                <Card key={story.id} className="rounded-[16px] border-border/40 bg-card/70 p-5">
                  <div className="flex flex-wrap items-start justify-between gap-3">
                    <div>
                      <div className="text-[11px] font-mono uppercase tracking-[0.16em] text-primary">{story.id}</div>
                      <h3 className="mt-1 text-xl font-semibold text-foreground">{story.title}</h3>
                      <p className="mt-2 max-w-3xl text-sm leading-relaxed text-muted-foreground">{story.summary}</p>
                    </div>
                    <Button onClick={() => void runStoryImplementation(story.id)} disabled={runningStoryId === story.id}>
                      {runningStoryId === story.id ? "Implementing..." : "Implement Story"}
                    </Button>
                  </div>

                  <div className="mt-5 grid gap-4 xl:grid-cols-3">
                    {story.variants.map((variant) => (
                      <VariantReviewCard
                        key={variant.id}
                        storyId={story.id}
                        variant={variant}
                        selected={story.selectedVariantId === variant.id}
                        onChoose={() => void chooseVariant(story.id, variant.id)}
                      />
                    ))}
                  </div>
                </Card>
              ))}
          </div>
        </div>

        {activeWorkspaceFile ? (
          <Card className="rounded-[16px] border-border/40 bg-card/70 p-4">
            <div className="flex items-center justify-between gap-3 border-b border-border/30 pb-3">
              <div>
                <div className="text-[11px] font-mono uppercase tracking-[0.16em] text-primary">Workspace File</div>
                <div className="mt-1 text-sm text-muted-foreground">{activeWorkspaceFile.path}</div>
              </div>
              <Badge variant="outline">{project.workspace.files.length} files</Badge>
            </div>
            <pre className="mt-4 min-h-[280px] overflow-auto rounded-[14px] border border-border/30 bg-[#0f172a] px-4 py-4 text-xs leading-relaxed text-slate-100">
              {activeWorkspaceFile.content}
            </pre>
          </Card>
        ) : null}

        <div className="flex justify-end">
          <Button
            disabled={project.userStories.some((story) => !story.selectedVariantId)}
            onClick={() => {
              if (!project.userStories.some((story) => !story.selectedVariantId)) {
                window.location.href = withProjectQuery("/merge", projectId)
              }
            }}
          >
            Continue To Testing & Integration
          </Button>
        </div>
      </div>
    </SDLCShell>
  )
}

function VariantReviewCard({
  storyId,
  variant,
  selected,
  onChoose,
}: {
  storyId: string
  variant: StoryVariant
  selected: boolean
  onChoose: () => void
}) {
  const securityText =
    variant.securityFindings?.length
      ? variant.securityFindings.map((item) => `${item.severity.toUpperCase()} · ${item.title}\n${item.detail}`).join("\n\n")
      : variant.securitySummary || "No security review stored yet"

  const tabs = useMemo(
    () => [
      { value: "overview", label: "Overview", content: variant.reasoning || "Not generated yet" },
      { value: "orchestration", label: "Delegation", content: variant.orchestration || "Not generated yet" },
      { value: "frontend", label: "Frontend", content: variant.frontendCode || "No frontend needed or not generated yet" },
      { value: "backend", label: "Backend", content: variant.backendCode || "Not generated yet" },
      { value: "security", label: "Security", content: securityText },
      {
        value: "tradeoffs",
        label: "Tradeoffs",
        content: `Pros\n${(variant.pros ?? []).join("\n") || "Waiting for evaluator"}\n\nCons\n${(variant.cons ?? []).join("\n") || "Waiting for evaluator"}`,
      },
    ],
    [securityText, variant]
  )

  return (
    <div className="overflow-hidden rounded-[24px] border border-border/30 bg-background/60">
      <div className="flex items-center justify-between gap-2 border-b border-border/30 px-4 py-3">
        <div>
          <div className="font-semibold text-foreground">{variant.label}</div>
          <div className="text-xs text-muted-foreground">{variant.teamName}</div>
        </div>
        <Badge variant="outline">{selected ? "Selected" : "Available"}</Badge>
      </div>

      <div className="px-4 py-4">
        <div className="mb-4 rounded-2xl bg-card/70 p-3">
          <div className="text-[10px] font-mono uppercase tracking-[0.14em] text-primary">Architecture</div>
          <p className="mt-2 text-sm leading-relaxed text-muted-foreground">{variant.architecture || "Agent-coordinated implementation"}</p>
        </div>

        <Tabs defaultValue="overview" className="gap-3">
          <TabsList className="h-auto w-full flex-wrap justify-start rounded-2xl bg-muted/60 p-1">
            {tabs.map((tab) => (
              <TabsTrigger key={`${storyId}-${variant.id}-${tab.value}`} value={tab.value} className="flex-none rounded-xl px-3 py-1.5 text-xs">
                {tab.label}
              </TabsTrigger>
            ))}
          </TabsList>
          {tabs.map((tab) => (
            <TabsContent key={`${variant.id}-${tab.value}`} value={tab.value}>
              <Block title={tab.label} content={tab.content} />
            </TabsContent>
          ))}
        </Tabs>

        <div className="mt-4">
          <Button size="sm" variant={selected ? "default" : "outline"} onClick={onChoose}>
            {selected ? "Selected For Preview" : `Choose ${variant.label}`}
          </Button>
        </div>
      </div>
    </div>
  )
}

function Block({ title, content }: { title: string; content: string }) {
  return (
    <div>
      <div className="text-[10px] font-mono uppercase tracking-[0.14em] text-muted-foreground">{title}</div>
      <pre className="mt-2 whitespace-pre-wrap rounded-xl border border-border/20 bg-card/60 px-3 py-2 text-xs leading-relaxed text-foreground/85">
        {content}
      </pre>
    </div>
  )
}
